// Reads dist/client/ and rewrites src/server/embedded-assets.ts to import
// every file with Bun's `with { type: "file" }` attribute. The resulting
// module exports a Map<urlPath, embeddedPath> that createApp.ts uses to serve
// static assets from inside the compiled binary.
//
// Run after `vite build` and before `bun build --compile`.

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");
const distRoot = join(repoRoot, "dist", "client");
const outPath = join(repoRoot, "src", "server", "embedded-assets.ts");

function walk(dir: string, base: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const stat = statSync(p);
    if (stat.isDirectory()) {
      out.push(...walk(p, base));
    } else {
      out.push(relative(base, p).replace(/\\/g, "/"));
    }
  }
  return out;
}

const files = walk(distRoot, distRoot);
files.sort();

const imports = files
  .map(
    (f, i) =>
      `import a${i} from "../../dist/client/${f}" with { type: "file" };`,
  )
  .join("\n");
const entries = files.map((f, i) => `  ["/${f}", a${i}],`).join("\n");

const out = `// Generated by scripts/embed-assets.ts. Do not edit.
${imports}

export const EMBEDDED_ASSETS: Map<string, string> | null = new Map<
  string,
  string
>([
${entries}
]);
`;

writeFileSync(outPath, out);
console.log(
  `[jampad] embedded ${files.length} assets from ${relative(repoRoot, distRoot)} → ${relative(repoRoot, outPath)}`,
);
